<?php

namespace kv4nt\yii2repeater;

use Yii;
use yii\base\Model;
use yii\base\Widget;
use yii\db\ActiveRecord;
use yii\helpers\Json;
use yii\widgets\ActiveForm;

class Repeater extends Widget
{

    /**
     * @var ActiveRecord[]
     */
    public $models;

    /**
     * @var string The view path to render repeater
     */
    public $modelView;

    /**
     * @var string The new item action url to run in ajax
     */
    public $appendAction;

    /**
     * @var string The remove item action url to run in ajax
     */
    public $removeAction;

    /**
     * @var ActiveForm Optional, if you want to use the $form variable.
     */
    public $form;

    /**
     * @var array Key - value params to append to the view file
     */
    public $additionalData = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $view = $this->getView();
        $this->view->registerJs('var deleteQuestionMessage="' . Yii::t('yii2-repeater', 'Do you really want to delete this item?') . '";', yii\web\View::POS_HEAD);
        RepeaterAsset::register($view);
        $data = Json::encode(['append' => $this->appendAction, 'remove' => $this->removeAction]);
        echo "<div class='ab-repeater'>";
        echo "<div class='list-area'>";
        foreach ($this->models as $k => $model)
        {
            $content = $this->render($this->modelView, array_merge(['model' => $model, 'form' => $this->form, 'id' => $model->id], $this->additionalData));
            echo $this->render('repeater', ['content' => $content, 'model' => $model, 'id' => $model->id]);
        }
        echo "</div><div class='row'><div class='col-xs-12 m-t-10 m-l-5'><a class='btn btn-primary new-repeater' href='javascript:;'>" . Yii::t('yii2-repeater', 'Add new item') . "</a> <a href='javascript:;' class='btn btn-danger recover-btn'>" . Yii::t('yii2-repeater', 'Recover') . "</a></div></div></div>";
        $js = "new window.repeater($data)";
        $this->view->registerJs($js);
    }

}
